name: blog_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0+1
  firebase_auth: "4.12.0"
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  get_it: ^7.6.7
  get_storage: ^2.1.1
  intl: ^0.19.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
